# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install -r requirements_dev.txt
        python -m pip install numpy==1.16.6
    - name: Typecheck with mypy
      run: |
        mypy --config-file mypy.ini longstaff_schwartz tests
    - name: Lint with flake8
      run: |
        flake8 longstaff_schwartz tests
    - name: Test with unittest
      run: |
        python -m unittest discover . -v
